name: ittjeenotes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: 0.18.1
  bottom_navy_bar: 5.5.0
  rxdart: 0.24.1
  intl: 0.16.1
  modal_bottom_sheet: 0.2.0+1
  flutter_pdfview: ^1.0.0+10
  contentful_rich_text: 0.1.2
  flutter_blurhash: 0.5.0
  firebase_core: 0.5.0
  firebase_auth: 0.18.0+1
  cloud_firestore: 0.14.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
   uses-material-design: true
   assets:
     - assets/icons/
   fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins/Poppins-Regular.ttf
     - family: Roboto Slab
       fonts:
         - asset: assets/fonts/Roboto_Slab/RobotoSlab-VariableFont_wght.ttf
